export default {
  color_green_good: "#23A454",
  color_yellow_neutral: "#FFB951",
  color_red_bad: "#E55B5B",
  color_primary: "#838C97",
  color_secondary: "#AFB8BF",
  color_brand: "#031946",
  color_brand_hover: "#06225f",
  color_button_hover: "#fafafa",
  color_date: "#ccc",
  color_notifications: "#de4733",
  color_dashboard_background: "#fafafa",
  color_sidebar_background: "#fff",
  color_button_active: "#e8e8e8",
  color_message_card_hover: "#f4f4f4",
  color_heading: "#000",
  color_dashboard_subheading: "#000",
  color_placeholder: "#e1e6ea",
  color_fail: "#f04640",
  color_fail_hover: "#d63d38",
  color_alert: "#dd5854",
  color_tooltip_primary: "#31363f",
  color_alert_text: "#FFF",
  color_alert_box_shadow: "0px 4px 8px rgba(221, 88, 84, 0.3)",
  color_input_box_shadow: "0px 0px 2px rgba(3, 24, 70, 0.3);",
  color_block_box_shadow: "0px 2px 4px rgba(0, 0, 0, 0.1)",
  color_slider_box_shadow: "0px 2px 4px rgba(0, 0, 0, 0.3)",
  font_size_primary: "1rem",
  font_size_secondary: "0.875rem",
  font_size_heading: "1.5rem",
  font_size_sidebar_heading: "1.125rem",
  font_size_dashboard_subheading: "1.125rem",
  font_size_tooltip: "0.688rem",
  font_weight_primary: "500",
  font_weight_secondary: "600",
  font_weight_subheading: "400",
  border_primary: "1px solid #e1e6ea",
  border_active: "1px solid #e8e8e8",
  border_light: "1px solid #fefefe",
  divider: "1px solid #E1E6EA",
  border_focus: "1px solid rgba(3, 24, 70, 0.6)",
  border_radius_primary: "4px",
  border_radius_secondary: "20px",
  border_radius_checkbox: "2px",
  transition_primary: "all 0.15s linear",
};
